# Generated by Django 3.1.4 on 2020-12-05 18:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_balance_margin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="balance",
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="margin",
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
    ]
