language: python
python: "3.9"
dist: focal
env:
  - DJANGO_SETTINGS_MODULE=kcsec.config.settings.local
cache:
  pip: true
install: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
script: poetry config virtualenvs.create false
before_script:
  - psql -c "CREATE DATABASE kcsec;" -U postgres
  - psql -c "CREATE USER kcsec;" -U postgres
services:
  - postgresql
  - redis
addons:
  postgresql: "10"
jobs:
  include:
    - stage: setup
    - install:
        - make migrate
        - poetry install
    - stage: lint
    - script:
        - poetry run black --check .
        - poetry run isort --check .
    - stage: test
      script: poetry run pytest -v --duration=0


