language: python
python: "3.9"
dist: bionic

branches:
  only:
  - master

env:
  global:
    - PGPORT=5432
    - DJANGO_SETTINGS_MODULE=kcsec.config.settings.local

cache:
  pip: true

services:
  - postgresql
  - redis
addons:
  postgresql: "10"

jobs:
  include:
    - stage: test and lint
      before_install:
        - pip install poetry
        - poetry config virtualenvs.create false
        - psql -c "CREATE USER kcsec SUPERUSER;" -U postgres
        - psql -c "CREATE DATABASE kcsec;" -U postgres
      install:
        - poetry install
        - make migrate
      script:
        - poetry run black --check .
        - poetry run isort --check .
        - poetry run pytest -v --durations=0

