version: '3'

volumes:
  pgdata: { }

services:
  web:
    build:
      context: .
      args:
        install_dev: "true"
    command: poetry run ./manage.py runserver 0.0.0.0:8000
    depends_on:
      - migrate-kcsec
    environment:
      - PUSHGATEWAY_HOST=http://pushgateway:9091
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-kcsec.config.settings.docker}
    ports:
      - 8000:8000
    volumes:
      - .:/app
  redis:
    image: redis:5.0.7-alpine
    ports:
      - 6379:6379

  migrate-kcsec:
    image: web
    entrypoint: poetry run python manage.py migrate
    environment:
      - POSTGRES_USER=kcsec
      - POSTGRES_PASSWORD=kcsec
      - POSTGRES_DB=kcsec
      - POSTGRES_HOST=kcsec
#  kcsec:
#    image: postgres:11
#    env_file:
#      - .env
#    environment:
#      - POSTGRES_HOST_AUTH_METHOD=trust  # need this to run without password
#    ports:
#      - 42069:5432
#    volumes:
#      - pgdata:/var/lib/postgresql/d
  # prometheus pushgateway
  pushgateway:
    image: prom/pushgateway:v1.2.0
    ports:
      - 9091:9091
  minio:
    image: minio/minio:RELEASE.2020-04-04T05-39-31Z
    command: [ "server", "/data" ]
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - 9000:9000
    volumes:
      - ./.data:/data

networks:
  default:
    external:
      name: kcsec-net
