version: '3'

volumes:
  pgdata: { }

services:
  kcsec:
    image: kcsec-web
    build:
      context: .
      args:
        install_dev: "true"
    command: "dev"
    depends_on:
      - migrate-kcsec
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-kcsec.config.settings.docker}
    ports:
      - 8000:8000
    volumes:
      - .:/app

  client:
    image: kcsec-web
    command: "client"
    depends_on:
      - migrate-kcsec
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-kcsec.config.settings.docker}
    volumes:
      - .:/app

  redis:
    image: redis:5.0.7-alpine
    ports:
      - 6379:6379

  migrate-kcsec:
    image: kcsec-web
    command: "migrate"
    depends_on:
      - kcsec-db
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-kcsec.config.settings.docker}
      - POSTGRES_USER=kcsec
      - POSTGRES_PASSWORD=kcsec
      - POSTGRES_DB=kcsec
      - POSTGRES_HOST=kcsec-db

  kcsec-db:
    image: postgres:11
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust  # need this to run without password
      - POSTGRES_USER=kcsec
      - POSTGRES_PASSWORD=kcsec
      - POSTGRES_DB=kcsec
    ports:
      - 42069:5432
    volumes:
      - pgdata:/var/lib/postgresql/d
  # prometheus pushgateway
#      - PUSHGATEWAY_HOST=http://pushgateway:9091
#  pushgateway:
#    image: prom/pushgateway:v1.2.0
#    ports:
#      - 9091:9091
#  minio:
#    image: minio/minio:RELEASE.2020-04-04T05-39-31Z
#    command: [ "server", "/data" ]
#    environment:
#      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
#      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
#    ports:
#      - 9000:9000
#    volumes:
#      - ./.data:/data

#networks:
#  default:
#    external:
#      name: kcsec-net
