apiVersion: v1
kind: Service
metadata:
  name: django-channels-service
  labels:
    pod: django-channels
    tier: websockets
spec:
  selector:
    pod: django-channels
  type: NodePort
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
