apiVersion: v1
kind: Service
metadata:
  name: crypto-consumer-service
  labels:
    pod: crypto-consumer-service
    tier: backend
spec:
  selector:
    pod: crypto-consumer-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002