apiVersion: v1
kind: Service
metadata:
  name: crypto-consumer-service
  labels:
    pod: crypto-consumer
    tier: frontend
spec:
  selector:
    pod: crypto-consumer
  type: NodePort
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30007