apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
        - name: paper-trader
          image: kevincybura/kcsec:local
          args: [ "migrate" ]
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: postgres-user
                  name: postgres-credentials

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: postgres-credentials

            - name: POSTGRES_NAME
              valueFrom:
                secretKeyRef:
                  key: postgres-name
                  name: postgres-credentials

            - name: POSTGRES_HOST
              value: postgres-service

            - name: DJANGO_SETTINGS_MODULE
              value: kcsec.config.settings.docker

      restartPolicy: Never
  backoffLimit: 5
