apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    pod: redis
    tier: backend
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    pod: redis
    tier: backend
