# Generated by Django 3.1 on 2020-08-29 18:36

import django.db.models.deletion
import psqlextra.manager.manager
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="price_usd",
            field=models.DecimalField(decimal_places=5, max_digits=50),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="price",
            field=models.DecimalField(decimal_places=5, max_digits=50),
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("time_exchange", models.DateTimeField()),
                ("time_coin_api", models.DateTimeField()),
                ("ask_price", models.DecimalField(decimal_places=5, max_digits=50)),
                ("ask_size", models.IntegerField()),
                ("bid_price", models.DecimalField(decimal_places=5, max_digits=50)),
                ("bid_size", models.IntegerField()),
                ("symbol_id", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="crypto.symbol")),
            ],
            options={
                "verbose_name": "Crypto currency quote",
                "verbose_name_plural": "Crypto currency quotes",
                "db_table": 'crypto"."quote',
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
