# Generated by Django 3.1.1 on 2020-09-06 15:58

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0003_auto_20200906_1459"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symbol",
            name="exchange",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="crypto.exchange"),
        ),
    ]
