# Generated by Django 3.1.1 on 2020-09-07 21:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0005_auto_20200906_1644"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="asset_icon",
            field=models.ImageField(null=True, upload_to="images/crypto/"),
        ),
        migrations.AddField(
            model_name="exchange",
            name="exchange_icon",
            field=models.ImageField(height_field=48, null=True, upload_to="images/crypto/", width_field=48),
        ),
        migrations.AddField(
            model_name="symbol",
            name="symbol_icon",
            field=models.ImageField(height_field=48, null=True, upload_to="images/crypto/", width_field=48),
        ),
    ]
