# Generated by Django 3.1.1 on 2020-09-12 17:53

import django.db.models.deletion
import psqlextra.manager.manager
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0006_auto_20200907_2134"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ohlcv",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("time_period_start", models.DateTimeField()),
                ("time_period_end", models.DateTimeField()),
                ("time_open", models.DateTimeField()),
                ("time_close", models.DateTimeField()),
                ("price_open", models.DecimalField(decimal_places=10, max_digits=25)),
                ("price_high", models.DecimalField(decimal_places=10, max_digits=25)),
                ("price_low", models.DecimalField(decimal_places=10, max_digits=25)),
                ("price_close", models.DecimalField(decimal_places=10, max_digits=25)),
                ("volume_traded", models.DecimalField(decimal_places=10, max_digits=25)),
                ("trades_count", models.IntegerField()),
                (
                    "asset_id_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name="ohlcv_base", to="crypto.asset"
                    ),
                ),
                (
                    "asset_id_quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name="ohlcv_quote", to="crypto.asset"
                    ),
                ),
            ],
            options={
                "verbose_name": "Open High Low Close Volume",
                "verbose_name_plural": "Open High Low Close Volume",
                "db_table": 'crypto"."ohlcv',
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
