# Generated by Django 3.1.1 on 2020-09-27 15:42

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0007_ohlcv"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ohlcv",
            old_name="price_close",
            new_name="close",
        ),
        migrations.RenameField(
            model_name="ohlcv",
            old_name="price_high",
            new_name="high",
        ),
        migrations.RenameField(
            model_name="ohlcv",
            old_name="price_low",
            new_name="low",
        ),
        migrations.RenameField(
            model_name="ohlcv",
            old_name="price_open",
            new_name="open",
        ),
        migrations.RenameField(
            model_name="ohlcv",
            old_name="volume_traded",
            new_name="volume",
        ),
        migrations.AddField(
            model_name="ohlcv",
            name="exchange",
            field=models.ForeignKey(
                default="back-filled", on_delete=django.db.models.deletion.DO_NOTHING, to="crypto.exchange"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ohlcv",
            name="time_close",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ohlcv",
            name="time_period_end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ohlcv",
            name="time_period_start",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ohlcv",
            name="trades_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name="ohlcv",
            unique_together={("exchange_id", "asset_id_base", "asset_id_quote", "time_open")},
        ),
    ]
