# Generated by Django 3.1.2 on 2020-10-25 17:22

import django.db.models.deletion
import psqlextra.manager.manager
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_portfolio"),
        ("crypto", "0008_auto_20200927_1542"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoShare",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=5, max_digits=15)),
                ("average_price", models.DecimalField(decimal_places=5, max_digits=15)),
                ("percent_gain", models.FloatField()),
                ("crypto_asset", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="crypto.symbol")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.portfolio")),
            ],
            options={
                "verbose_name": "Crypto currency share",
                "verbose_name_plural": "Crypto currency shares",
                "db_table": 'crypto"."share',
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="CryptoOrder",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=5, max_digits=15)),
                ("quantity", models.DecimalField(decimal_places=5, max_digits=15)),
                ("filled", models.BooleanField()),
                ("share", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crypto.cryptoshare")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.portfolio")),
            ],
            options={
                "verbose_name": "Crypto currency order",
                "verbose_name_plural": "Crypto currency order",
                "db_table": 'crypto"."order',
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
