# Generated by Django 3.1.4 on 2020-12-05 18:07

import django.db.models.deletion
import psqlextra.manager.manager
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_portfolio_margin_balance_annon_user"),
        ("crypto", "0008_auto_20200927_1542"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoShare",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("shares", models.DecimalField(decimal_places=5, max_digits=15)),
                ("average_price", models.DecimalField(decimal_places=5, max_digits=15)),
                (
                    "crypto_symbol",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="crypto.symbol"),
                ),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.portfolio")),
            ],
            options={
                "verbose_name": "Crypto currency share",
                "verbose_name_plural": "Crypto currency shares",
                "db_table": 'crypto"."share',
                "unique_together": {("portfolio", "crypto_symbol")},
            },
        ),
        migrations.CreateModel(
            name="CryptoOrder",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=5, max_digits=15)),
                ("shares", models.DecimalField(decimal_places=5, max_digits=15)),
                ("filled", models.BooleanField(default=False)),
                ("order_type", models.CharField(choices=[("buy", "Buy"), ("sell", "Sell")], max_length=5)),
                (
                    "crypto_symbol",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="crypto.symbol"),
                ),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="core.portfolio")),
                (
                    "share",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="crypto.cryptoshare"
                    ),
                ),
            ],
            options={
                "verbose_name": "Crypto currency order",
                "verbose_name_plural": "Crypto currency order",
                "db_table": 'crypto"."order',
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
