# Generated by Django 3.1.4 on 2020-12-13 17:38

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0009_share_and_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptoorder",
            name="trade_type",
            field=models.CharField(choices=[("buy", "Buy"), ("sell", "Sell")], default="buy", max_length=5),
        ),
        migrations.AlterField(
            model_name="cryptoorder",
            name="order_type",
            field=models.CharField(
                choices=[("market_order", "Market Order"), ("limit_order", "Limit Order")],
                default="market_order",
                max_length=20,
            ),
        ),
    ]
