# Generated by Django 3.1.4 on 2020-12-13 20:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0010_order_and_trade_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptoshare",
            name="percent_change",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
    ]
