# Generated by Django 3.1.4 on 2020-12-20 20:42

from django.db import migrations
from django.db import models

import kcsec.crypto.models._managers


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0011_share_percent_change"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="ohlcv",
            managers=[
                ("objects", kcsec.crypto.models._managers.OhlcvManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="symbol",
            managers=[],
        ),
        migrations.AddField(
            model_name="ohlcv",
            name="time_frame",
            field=models.CharField(
                choices=[
                    ("1m", "One Minute"),
                    ("5m", "Five Minute"),
                    ("15m", "Fifteen Minute"),
                    ("30m", "Thirty Minute"),
                    ("1h", "One Hour"),
                    ("6h", "Six Hour"),
                    ("1d", "One Day"),
                ],
                default="1m",
                max_length=3,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="ohlcv",
            unique_together={("exchange_id", "asset_id_base", "asset_id_quote", "time_open", "time_frame")},
        ),
    ]
