# Generated by Django 3.1.4 on 2020-12-22 19:57

import django.db.models.deletion
from django.db import migrations
from django.db import models

import kcsec.crypto.models._managers


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0012_ohlcv_timeframe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ohlcv",
            options={
                "get_latest_by": ["time_open"],
                "ordering": ["time_open"],
                "verbose_name": "Open High Low Close Volume",
                "verbose_name_plural": "Open High Low Close Volume",
            },
        ),
        migrations.AlterModelManagers(
            name="symbol",
            managers=[
                ("objects", kcsec.crypto.models._managers.SymbolManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="asset",
            name="data_end",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="data_orderbook_end",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="data_orderbook_start",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="data_quote_end",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="data_quote_start",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="data_start",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="data_symbols_count",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="data_trade_end",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="data_trade_start",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="volume_1day_usd",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="volume_1hrs_usd",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="volume_1mth_usd",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="data_end",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="data_orderbook_end",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="data_orderbook_start",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="data_quote_end",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="data_quote_start",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="data_symbols_count",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="data_trade_end",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="data_trade_start",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="volume_1day_usd",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="volume_1hrs_usd",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="volume_1mth_usd",
        ),
        migrations.AddField(
            model_name="ohlcv",
            name="symbol",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to="crypto.symbol"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="symbol",
            name="asset_id_base",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, related_name="base", to="crypto.asset"
            ),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="asset_id_quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, related_name="quote", to="crypto.asset"
            ),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="exchange",
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="crypto.exchange"),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="symbol_type",
            field=models.CharField(choices=[("crypto", "Crypto")], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name="ohlcv",
            unique_together={("symbol", "exchange", "time_open", "time_frame")},
        ),
        migrations.RemoveField(
            model_name="ohlcv",
            name="time_period_end",
        ),
        migrations.RemoveField(
            model_name="ohlcv",
            name="time_period_start",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="asset_id_unit",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="data_end",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="data_orderbook_end",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="data_orderbook_start",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="data_quote_end",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="data_quote_start",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="data_start",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="data_trade_end",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="data_trade_start",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="symbol_id",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="volume_1day",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="volume_1day_usd",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="volume_1hrs",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="volume_1hrs_usd",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="volume_1mth",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="volume_1mth_usd",
        ),
        migrations.AddField(
            model_name="symbol",
            name="id",
            field=models.CharField(default=None, max_length=150, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="symbol",
            unique_together={("id", "exchange")},
        ),
    ]
