# Generated by Django 3.1.4 on 2020-12-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_portfolio_margin_balance_annon_user"),
        ("crypto", "0013_remove_not_used_and_refactor_composite_keys"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cryptoorder",
            old_name="crypto_symbol",
            new_name="symbol",
        ),
        migrations.RenameField(
            model_name="cryptoshare",
            old_name="crypto_symbol",
            new_name="symbol",
        ),
        migrations.AlterUniqueTogether(
            name="cryptoshare",
            unique_together={("portfolio", "symbol")},
        ),
        migrations.RemoveField(
            model_name="cryptoshare",
            name="percent_change",
        ),
    ]
