name: Kcsec
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: 11
          postgresql db: kcsec
          postgresql user: kcsec

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4

      - name: Cache poetry install
        uses: actions/cache@v2.1.3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-

      - name: Install dependencies
        run: poetry install

      - name: Format
        run: |
          poetry run black --check .
          poetry run isort --check .

      - name: Migrate
        run: poetry run ./manage.py migrate

      - name: Test with pytest
        run: poetry run pytest -v --durations=0
