apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: postgres-container
  template:
    metadata:
      labels:
        pod: postgres-container
        tier: backend
    spec:
      containers:
        - name: postgres-container
          imagePullPolicy: Always
          image: postgres:12.5
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: postgres-user
                  name: postgres-credentials

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: postgres-credentials

            - name: POSTGRES_DB
              value: paper-trader-db

          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pvc

